services:
  - type: web
    name: cafeteria-react
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://cafeteria-backend-bn7o.onrender.com/api
